from .standard import (
    MAP_DEF as STANDARD_MAP_DEF,
    NEUTRAL_CENTERS as STANDARD_NEUTRAL_CENTERS,
    POWERS as STANDARD_POWERS,
    STARTING_UNITS as STANDARD_STARTING_UNITS,
)
from .triangle3 import CONTESTED_CENTER, MAP_DEF, NEUTRAL_CENTERS, POWERS, STARTING_UNITS

__all__ = [
    "CONTESTED_CENTER",
    "MAP_DEF",
    "NEUTRAL_CENTERS",
    "POWERS",
    "STANDARD_MAP_DEF",
    "STANDARD_NEUTRAL_CENTERS",
    "STANDARD_POWERS",
    "STANDARD_STARTING_UNITS",
    "STARTING_UNITS",
]
