"""Standard Diplomacy board map definition."""

from __future__ import annotations

from dip_tom.env.map import MapDef

POWERS = (
    "England",
    "France",
    "Germany",
    "Italy",
    "Austria",
    "Russia",
    "Turkey",
)

MAP_DEF = MapDef(
    name="standard",
    nodes=(
        "NAO",
        "MAO",
        "IRI",
        "ENG",
        "CLY",
        "LVP",
        "WAL",
        "LON",
        "YOR",
        "EDI",
        "NWG",
        "BAR",
        "NTH",
        "NWY",
        "SKA",
        "DEN",
        "HEL",
        "SWE",
        "BAL",
        "BOT",
        "FIN",
        "STP",
        "LVN",
        "PRU",
        "MOS",
        "WAR",
        "SEV",
        "BLA",
        "UKR",
        "GAL",
        "SIL",
        "KIE",
        "BER",
        "MUN",
        "BOH",
        "TYR",
        "VIE",
        "BUD",
        "TRI",
        "RUM",
        "SER",
        "BUL",
        "CON",
        "ANK",
        "SMY",
        "ARM",
        "SYR",
        "ALB",
        "GRE",
        "AEG",
        "ION",
        "EAS",
        "ADR",
        "VEN",
        "ROM",
        "NAP",
        "TUS",
        "PIE",
        "APU",
        "TUN",
        "NAF",
        "WES",
        "TYS",
        "LYO",
        "MAR",
        "SPA",
        "POR",
        "GAS",
        "BUR",
        "PAR",
        "BRE",
        "PIC",
        "BEL",
        "RUH",
        "HOL",
    ),
    edges=(
        ("ADR", "ALB"),
        ("ADR", "APU"),
        ("ADR", "ION"),
        ("ADR", "TRI"),
        ("ADR", "VEN"),
        ("AEG", "BUL"),
        ("AEG", "CON"),
        ("AEG", "EAS"),
        ("AEG", "GRE"),
        ("AEG", "ION"),
        ("AEG", "SMY"),
        ("ALB", "GRE"),
        ("ALB", "ION"),
        ("ALB", "SER"),
        ("ALB", "TRI"),
        ("ANK", "ARM"),
        ("ANK", "BLA"),
        ("ANK", "CON"),
        ("ANK", "SMY"),
        ("APU", "ION"),
        ("APU", "NAP"),
        ("APU", "ROM"),
        ("APU", "VEN"),
        ("ARM", "BLA"),
        ("ARM", "SEV"),
        ("ARM", "SMY"),
        ("ARM", "SYR"),
        ("BAL", "BER"),
        ("BAL", "BOT"),
        ("BAL", "DEN"),
        ("BAL", "HEL"),
        ("BAL", "KIE"),
        ("BAL", "LVN"),
        ("BAL", "PRU"),
        ("BAL", "SWE"),
        ("BAR", "NWG"),
        ("BAR", "NWY"),
        ("BAR", "STP"),
        ("BEL", "BUR"),
        ("BEL", "ENG"),
        ("BEL", "HOL"),
        ("BEL", "NTH"),
        ("BEL", "PIC"),
        ("BEL", "RUH"),
        ("BER", "KIE"),
        ("BER", "MUN"),
        ("BER", "PRU"),
        ("BER", "SIL"),
        ("BLA", "BUL"),
        ("BLA", "CON"),
        ("BLA", "RUM"),
        ("BLA", "SEV"),
        ("BOH", "GAL"),
        ("BOH", "MUN"),
        ("BOH", "SIL"),
        ("BOH", "TYR"),
        ("BOH", "VIE"),
        ("BOT", "FIN"),
        ("BOT", "LVN"),
        ("BOT", "STP"),
        ("BOT", "SWE"),
        ("BRE", "ENG"),
        ("BRE", "GAS"),
        ("BRE", "MAO"),
        ("BRE", "PAR"),
        ("BRE", "PIC"),
        ("BUD", "GAL"),
        ("BUD", "RUM"),
        ("BUD", "SER"),
        ("BUD", "TRI"),
        ("BUD", "VIE"),
        ("BUL", "CON"),
        ("BUL", "GRE"),
        ("BUL", "RUM"),
        ("BUL", "SER"),
        ("BUR", "GAS"),
        ("BUR", "MAR"),
        ("BUR", "MUN"),
        ("BUR", "PAR"),
        ("BUR", "PIC"),
        ("BUR", "RUH"),
        ("CLY", "EDI"),
        ("CLY", "LVP"),
        ("CLY", "NAO"),
        ("CLY", "NWG"),
        ("CON", "SMY"),
        ("DEN", "HEL"),
        ("DEN", "KIE"),
        ("DEN", "NTH"),
        ("DEN", "SKA"),
        ("DEN", "SWE"),
        ("EAS", "ION"),
        ("EAS", "SMY"),
        ("EAS", "SYR"),
        ("EDI", "LVP"),
        ("EDI", "NTH"),
        ("EDI", "NWG"),
        ("EDI", "YOR"),
        ("ENG", "IRI"),
        ("ENG", "LON"),
        ("ENG", "MAO"),
        ("ENG", "NTH"),
        ("ENG", "PIC"),
        ("ENG", "WAL"),
        ("FIN", "NWY"),
        ("FIN", "STP"),
        ("FIN", "SWE"),
        ("GAL", "RUM"),
        ("GAL", "SIL"),
        ("GAL", "UKR"),
        ("GAL", "VIE"),
        ("GAL", "WAR"),
        ("GAS", "MAO"),
        ("GAS", "MAR"),
        ("GAS", "PAR"),
        ("GAS", "SPA"),
        ("GRE", "ION"),
        ("GRE", "SER"),
        ("HEL", "HOL"),
        ("HEL", "KIE"),
        ("HEL", "NTH"),
        ("HOL", "KIE"),
        ("HOL", "NTH"),
        ("HOL", "RUH"),
        ("ION", "NAP"),
        ("ION", "TUN"),
        ("ION", "TYS"),
        ("IRI", "LVP"),
        ("IRI", "MAO"),
        ("IRI", "NAO"),
        ("IRI", "WAL"),
        ("KIE", "MUN"),
        ("KIE", "RUH"),
        ("LON", "NTH"),
        ("LON", "WAL"),
        ("LON", "YOR"),
        ("LVN", "MOS"),
        ("LVN", "PRU"),
        ("LVN", "STP"),
        ("LVN", "WAR"),
        ("LVP", "NAO"),
        ("LVP", "WAL"),
        ("LVP", "YOR"),
        ("LYO", "MAR"),
        ("LYO", "PIE"),
        ("LYO", "SPA"),
        ("LYO", "TUS"),
        ("LYO", "TYS"),
        ("LYO", "WES"),
        ("MAO", "NAF"),
        ("MAO", "NAO"),
        ("MAO", "POR"),
        ("MAO", "SPA"),
        ("MAO", "WES"),
        ("MAR", "PIE"),
        ("MAR", "SPA"),
        ("MOS", "SEV"),
        ("MOS", "STP"),
        ("MOS", "UKR"),
        ("MOS", "WAR"),
        ("MUN", "RUH"),
        ("MUN", "SIL"),
        ("MUN", "TYR"),
        ("NAF", "TUN"),
        ("NAF", "WES"),
        ("NAO", "NWG"),
        ("NAP", "ROM"),
        ("NAP", "TYS"),
        ("NTH", "NWG"),
        ("NTH", "NWY"),
        ("NTH", "SKA"),
        ("NTH", "YOR"),
        ("NWG", "NWY"),
        ("NWY", "SKA"),
        ("NWY", "STP"),
        ("NWY", "SWE"),
        ("PAR", "PIC"),
        ("PIE", "TUS"),
        ("PIE", "TYR"),
        ("PIE", "VEN"),
        ("POR", "SPA"),
        ("PRU", "SIL"),
        ("PRU", "WAR"),
        ("ROM", "TUS"),
        ("ROM", "TYS"),
        ("ROM", "VEN"),
        ("RUM", "SER"),
        ("RUM", "SEV"),
        ("RUM", "UKR"),
        ("SER", "TRI"),
        ("SEV", "UKR"),
        ("SIL", "WAR"),
        ("SKA", "SWE"),
        ("SMY", "SYR"),
        ("SPA", "WES"),
        ("TRI", "TYR"),
        ("TRI", "VEN"),
        ("TRI", "VIE"),
        ("TUN", "TYS"),
        ("TUN", "WES"),
        ("TUS", "TYR"),
        ("TUS", "TYS"),
        ("TUS", "VEN"),
        ("TYR", "VEN"),
        ("TYR", "VIE"),
        ("TYS", "WES"),
        ("UKR", "WAR"),
    ),
    supply_centers=(
        "LVP",
        "LON",
        "EDI",
        "NWY",
        "DEN",
        "SWE",
        "STP",
        "MOS",
        "WAR",
        "SEV",
        "KIE",
        "BER",
        "MUN",
        "VIE",
        "BUD",
        "TRI",
        "RUM",
        "SER",
        "BUL",
        "CON",
        "ANK",
        "SMY",
        "GRE",
        "VEN",
        "ROM",
        "NAP",
        "TUN",
        "MAR",
        "SPA",
        "POR",
        "PAR",
        "BRE",
        "BEL",
        "HOL",
    ),
    home_centers={
        "England": ("LVP", "LON", "EDI"),
        "France": ("MAR", "PAR", "BRE"),
        "Germany": ("KIE", "BER", "MUN"),
        "Italy": ("VEN", "ROM", "NAP"),
        "Austria": ("VIE", "BUD", "TRI"),
        "Russia": ("STP", "MOS", "WAR", "SEV"),
        "Turkey": ("CON", "ANK", "SMY"),
    },
)

STARTING_UNITS = {
    "England": {"LVP": "LVP", "LON": "LON", "EDI": "EDI"},
    "France": {"PAR": "PAR", "MAR": "MAR", "BRE": "BRE"},
    "Germany": {"KIE": "KIE", "BER": "BER", "MUN": "MUN"},
    "Italy": {"VEN": "VEN", "ROM": "ROM", "NAP": "NAP"},
    "Austria": {"VIE": "VIE", "BUD": "BUD", "TRI": "TRI"},
    "Russia": {"STP": "STP", "MOS": "MOS", "WAR": "WAR", "SEV": "SEV"},
    "Turkey": {"CON": "CON", "ANK": "ANK", "SMY": "SMY"},
}

NEUTRAL_CENTERS = (
    "NWY",
    "DEN",
    "SWE",
    "RUM",
    "SER",
    "BUL",
    "GRE",
    "TUN",
    "SPA",
    "POR",
    "BEL",
    "HOL",
)
